export interface Receipt {
  // Document ID (auto-generated by Firestore)
  id: string;

  // User relationship
  userId: string; // Firebase Auth UID
  userEmail: string;

  // Seller Information (Required by Norwegian law)
  sellerName: string;
  sellerOrgNumber?: string; // Organizasjonsnummer
  sellerAddress?: string; // Salgs-/leveringssted

  // Buyer Information (Required in some cases)
  buyerName?: string;
  buyerAddress?: string;
  buyerOrgNumber?: string;

  // Receipt Details
  receiptNumber?: string; // Kvitteringsnummer
  receiptDate: Date; // Transaction date

  // Financial Information
  totalAmount: number; // Total including VAT
  subtotal: number; // Amount before VAT
  vatAmount: number; // MVA-beløp
  vatRate?: number; // MVA-sats (25%, 15%, 12%, etc.)
  currency: string; // Default: "NOK"

  // Line Items (Products/Services)
  items: ReceiptItem[];

  // Payment Information
  paymentMethod?: "card" | "cash" | "mobile" | "invoice" | "other";
  cardType?: string; // Visa, Mastercard, etc.

  // Image & OCR Data
  imageUrl: string; // Firebase Storage URL
  imagePath: string; // Storage path for deletion
  ocrRawText?: string; // Raw text from Google Cloud Vision
  ocrConfidence?: number; // OCR confidence score (0-1)

  // Metadata
  createdAt: Date;
  updatedAt: Date;
  status: "pending" | "processed" | "verified" | "archived";

  // Categories & Tags
  category?: ReceiptCategory;
  tags?: string[];
  notes?: string;

  // Verification
  isVerified: boolean; // User manually verified the data
  hasVAT: boolean; // MVA applicable
}

export interface ReceiptItem {
  id: string;
  name: string; // Product/service name
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  vatRate?: number;
  vatAmount?: number;
  category?: string;
}

export type ReceiptCategory =
  | "food_drink" // Mat og drikke
  | "transportation" // Transport
  | "office_supplies" // Kontorrekvisita
  | "entertainment" // Underholdning
  | "utilities" // Strøm, vann, etc.
  | "equipment" // Utstyr
  | "services" // Tjenester
  | "clothing" // Klær
  | "electronics" // Elektronikk
  | "other"; // Annet
